{% set name = "opentelemetry-resourcedetector-gcp" %}
{% set version = "1.7.0a0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 70e49a9ec282089cae60c450fc9fa1bb63eafac2e1747acb9603574f430e3666

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - opentelemetry-api >=1.0,<2.dev0
    - opentelemetry-sdk >=1.0,<2.dev0
    - requests >=2.24,<3.dev0
    - typing-extensions >=4.0,<5.dev0

test:
  imports:
    - opentelemetry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/tree/main/opentelemetry-resourcedetector-gcp
  summary: Google Cloud resource detector for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
